name: Conditional
on: 
  push:

permissions: read-only

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        id: checkout
        uses: actions/checkout@v4
      # Do some imaginary testing
      - name: Failed Test Report
        if: failure() && steps.checkout.outcome == 'failed'
      # Only print this if the test report failed
        run: echo "Test Failed, upload artifact"
  build:
    # Run this workflow if some job failed
    if: failure()
    runs-on: ubuntu-latest
    steps:
     - name: Output Error Message
      run: echo "Something failed"