name: Reusable
on:
  workflow_call:
    inputs: 
      artifact-name:
        description: The name of the deploybale artifact file
        required: true
        default: dist
        tpye: string
    outputs:
      artifact:
        description: The artifact after the build process
        value: ${{ jobs.test.outputs.result }}

jobs:
  test:
    runs-on: windows-latest
    outputs:
      result: ${{ steps.status.outputs.result }}
    steps:
      - name: Use Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls    
      - name: Output
        run: echo "outputing something..."
      - name: status
        id: status
        run: echo "result=success" >> $GITHUB_OUTPUT