name: Using Reusable Workflow
on: 
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Testing something
        run: echo "testing something"
  build:
    needs: test
    uses: ./.github/workflows/reusable.yml